### ISSUE TITLE
Can you please maintain README.md file for this project?

### ISSUE THREAD

**Issue by mail2chromium** [dhelmrich/Synavis#2]
Well, You are doing great work. I have just started Unreal Engine a couple of days ago. I have been trying to implement **Forward Unreal Engine pixel streaming to a WebRTC peer that then forwards the RTP streams to the desired address.**

> Actually, If you manage to write README.md, it would help others to understand and appreciate your work so far.

I hope your repo might help me to do that. Looking forward to speaking with you soon.

Thanks

**Comment by dhelmrich** [comment]
Good Idea, I'll do that right now! We have internal documentation on my progress in this regard, but it would help to have something for all to see.

**Comment by dhelmrich** [comment]
I added the readme now - if you have any further questions, just use the issue tracker.
